name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # This triggers the workflow on pull requests targeting 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify your desired Terraform version

      # Step 3: Set up AWS credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Specify your AWS region

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Apply Terraform Configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply the configuration automatically

